# Workflow intended to periodically test containerd integration tests

name: Windows Periodic Tests

on:
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}

jobs:
  winIntegration:
    strategy:
      matrix:
        win_ver: [ltsc2019, sac2004, ltsc2022]
        include:
        - win_ver: sac2004
          AZURE_IMG: "MicrosoftWindowsServer:WindowsServer:datacenter-core-2004-with-containers-smalldisk:19041.928.2104150521"
          AZURE_RESOURCE_GROUP: ctrd-integration-sac2004-${{ github.run_id }}
          GOOGLE_BUCKET: "gs://containerd-integration/logs/windows-sac2004/"
        - win_ver: ltsc2019
          AZURE_IMG: "MicrosoftWindowsServer:WindowsServer:2019-Datacenter-with-Containers-smalldisk:17763.1935.2105080716"
          AZURE_RESOURCE_GROUP: ctrd-integration-ltsc2019-${{ github.run_id }}
          GOOGLE_BUCKET: "gs://containerd-integration/logs/windows-ltsc2019/"
        - win_ver: ltsc2022
          AZURE_IMG: "MicrosoftWindowsServer:WindowsServer:2022-datacenter-smalldisk-g2:20348.169.2108120020"
          AZURE_RESOURCE_GROUP: ctrd-integration-ltsc2022-${{ github.run_id }}
          GOOGLE_BUCKET: "gs://containerd-integration/logs/windows-ltsc2022/"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AZLogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
