# Workflow intended to periodically run the Windows Hyper-V Benchmarking workflow.

name: Windows Hyper-V Benchmarks Trigger

on:
  workflow_dispatch:
  schedule:
    # NOTE: benchmarks should run twice a month:
    - cron: "* * 1 * *"
    - cron: "* * 15 * *"

jobs:

  triggerWinIntegration:
    if: github.repository == 'containerd/containerd'
    # NOTE(aznashwan, 6/6/2022): GitHub actions do not currently support referencing
    # or evaluating any kind of variables in the `uses` clause, but this will
    # ideally be added in the future in which case the hardcoded reference to the
    # upstream containerd repository should be replaced with the following to
    # potentially allow contributors to enable periodic Windows benchmarks on forks as well:
    # uses: "${{ github.repository }}/.github/workflows/windows-benchmarks.yml@${{ github.ref_name }}"
    uses: containerd/containerd/.github/workflows/windows-hyperv-benchmarks.yml@main
    with:
      hcsshimVersion: auto
      containersNumber: 500
      containersNumberParallel: 1
      imagesNumber: 500
      imagesNumberParallel: 1
      podsNumber: 500
      podsNumberParallel: 1
    secrets:
      AZURE_SUB_ID: "${{ secrets.AZURE_SUB_ID }}"
      AZURE_CREDS: "${{ secrets.AZURE_CREDS }}"
      GCP_SERVICE_ACCOUNT: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
      GCP_WORKLOAD_IDENTITY_PROVIDER: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
